version: '3'
services:
  vprodb:
    image: bumeranghc/mysql:V1
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=accounts
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
  vproapp:
    image: bumeranghc/tomcat:V1
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps
  vproweb:
    image: bumeranghc/nginx:V1
    ports:
      - "80:80"
volumes:
  vprodbdata: {}
  vproappdata: {} 