- name: Setup Tomcat8 & Deploy Artifact
  hosts: appsrvgrp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"

  tasks:

    - name: Download latest VProfile.war from nexus
      get_url:
        url: "http://{{nexus_user}}:{{nexus_password}}@{{nexusip}}:{{nexusport}}/repository/{{reponame}}/{{groupid}}/{{artifactId}}/{{vprofile_version}}/{{artifactId}}-{{vprofile_version}}.war"
        dest: "/tmp/vproapp-{{vprofile_version}}.war"
      register: wardeploy
      tags:
       - deploy
